import Forbidden from './components/Forbidden.vue';
import ErrorSummary from './components/ErrorSummary.vue';
import Input from './components/Input.vue';
import Select from './components/Select.vue';
import CheckBox from './components/CheckBox.vue';
import Button from './components/Button.vue';
import SvgImage from './components/SvgImage.vue';
import Link from './components/Link.vue';
import LinkButton from './components/LinkButton.vue';
import Nav from './components/Nav.vue';
import Navbar from './components/Navbar.vue';
import NavLink from './components/NavLink.vue';
import NavButtonGroup from './components/NavButtonGroup.vue';
import NavLinkButton from './components/NavLinkButton.vue';
declare function install(Vue: any): void;
declare const plugin: {
    install: typeof install;
};
export default plugin;
export { Forbidden, ErrorSummary, Input, Select, CheckBox, Button, SvgImage, Link, LinkButton, Nav, Navbar, NavLink, NavButtonGroup, NavLinkButton, };
